name: C/C++ CI

on:
  push:
    branches: [ master, feat/new-code ]
  pull_request:
    branches: [ master, feat/new-code ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
